# Generated by Django 2.2 on 2019-04-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_excelcase_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelcase',
            name='assessment',
            field=models.CharField(max_length=100, null=True, verbose_name='评审结果'),
        ),
    ]
